#!/bin/bash
#  __  __     __  __     ______   ______     __  __     ______     __   __   ______     __   __
# /\ \_\ \   /\ \_\ \   /\  == \ /\  == \   /\ \_\ \   /\  __ \   /\ \ / /  /\  ___\   /\ "-.\ \
# \ \  __ \  \ \____ \  \ \  _-/ \ \  __<   \ \  __ \  \ \  __ \  \ \ \'/   \ \  __\   \ \ \-.  \
#  \ \_\ \_\  \/\_____\  \ \_\    \ \_\ \_\  \ \_\ \_\  \ \_\ \_\  \ \__|    \ \_____\  \ \_\\"\_\
#   \/_/\/_/   \/_____/   \/_/     \/_/ /_/   \/_/\/_/   \/_/\/_/   \/_/      \/_____/   \/_/ \/_/
#
# Requires jq and needs to be ran on start alongside of hyprpaper. Can be ran multiple times

WALLPAPER_DIR="/tmp/"
WALLPAPER_DEFAULT_DIR="${HOME}/.local/share/wallpapers/"

# Setting up search query params
# https://wallhaven.cc/help/api#search

# Presets
# PRESET="classic-art"
###############
# Classic art #
###############
# QUERY_LIST=("classic art")
# CATEGORIES=111
# PURITY=110
# COLOR_LIST=("663399" "333399" "0066cc")

##############
# Cityscapes #
##############
# QUERY_LIST=("city|cityscape")
# CATEGORIES=101
# PURITY=100
# COLOR_LIST=("663399" "333399" "0066cc")

PRESET="cityscapes"
# COLOR_LIST=("663399" "333399" "0066cc")

if [ $1 ]; then
    PRESET=$1
fi

case $PRESET in
"classic-art")
    SORTING="favorites"
    QUERY_LIST=("classic art")
    CATEGORIES=111
    PURITY=110
    ;;
"landscape")
    SORTING="favorites"
    QUERY_LIST=("landscape&nature")
    CATEGORIES=100
    PURITY=100
    ;;
"cyberpunk")
    SORTING="favorites"
    QUERY_LIST=("cyberpunk")
    CATEGORIES=110
    PURITY=100
    ;;
"abstract")
    SORTING="favorites"
    QUERY_LIST=("absctract|shapes")
    CATEGORIES=100
    PURITY=100
    ;;
"cityscapes")
    SORTING="favorites"
    QUERY_LIST=("city|cityscape")
    CATEGORIES=101
    PURITY=100
    ;;
"anime")
    SORTING="favorites"
    CATEGORIES=010
    PURITY=100
    ;;
"anime-spicy")
    SORTING="favorites"
    CATEGORIES=010
    PURITY=010
    ;;
"top1d")
    SORTING="toplist"
    TOPRANGE="1d"
    PURITY=100
    ;;
"top1w")
    SORTING="toplist"
    TOPRANGE="1w"
    PURITY=100
    ;;
"top1m")
    SORTING="toplist"
    TOPRANGE="1M"
    PURITY=100
    ;;
"top1y")
    SORTING="toplist"
    TOPRANGE="1y"
    PURITY=100
    ;;
"random")
    SORTING="random"
    CATEGORIES=111
    PURITY=100
    ;;
esac

QUERY=$(
    IFS=','
    echo "${QUERY_LIST[*]}" | sed 's/ /+/g'
)

# Available colors
# #660000 #990000 #cc0000 #cc3333 #ea4c88
# #993399 #663399 #333399 #0066cc #0099cc
# #66cccc #77cc33 #669900 #336600 #666600
# #999900 #cccc33 #ffff00 #ffcc33 #ff9900
# #ff6600 #cc6633 #996633 #663300 #000000
# #999999 #cccccc #ffffff #424153
# !Remove # before pasting colors
# COLOR_LIST=("660000 990000 cc0000 cc3333 ea4c88 993399 663399 333399 0066cc 0099cc 66cccc 77cc33 669900 336600 666600 999900 cccc33 ffff00 ffcc33 ff9900 ff6600 cc6633 996633 663300 000000 999999 cccccc ffffff 424153")

# Join colors into string like "663399,333399,0066cc" for wallhaven api
COLORS=$(
    IFS=','
    echo "${COLOR_LIST[*]}"
)

# How many pages to fetch
FETCH_PAGES=10

# Image categories
# 100/010/001 (general/anime/people)
# CATEGORIES=111

# Image purity
# 100/010/001 (sfw/sketchy/nsfw)
# PURITY=100

# Sorting algorithm
# date_added, relevance, random, views, favorites, toplist
# SORTING="favorites"

MIN_RES="1920x1080"

# All wide
RATIOS="landscape"

kill_instance() {
    # Find current instance name and PID
    SCRIPT_NAME=$(basename "$0")
    CURRENT_PID=$$

    # Kill all other instances
    # Careful, it kills not just instances, just anything that has hyprhaven name in it
    if [ $(pgrep -f "$SCRIPT_NAME" | wc -l) -gt 2 ]; then
        OLD_PIDS=$(pgrep -f "$SCRIPT_NAME")
        for PID in $OLD_PIDS; do
            if [ "$PID" != "$CURRENT_PID" ]; then
                echo "Killing old instance with PID: $PID"
                kill "$PID"
            fi
        done
    fi
}

set_wallpaper() {
    # Unload previous wallpaper
    for WALLPAPER in $(hyprctl hyprpaper listloaded); do
        hyprctl hyprpaper unload "$WALLPAPER"
    done

    # Load new wallpaper
    for monitor in $(hyprctl monitors | grep "Monitor" | cut -d " " -f 2); do
        hyprctl hyprpaper preload $IMAGE
        hyprctl hyprpaper wallpaper "$monitor,$IMAGE"
    done
}

generate_url() {
    URL="https://wallhaven.cc/api/v1/search?"
    # Query should always be set, even though it's empty or non existent just to start params string
    URL="${URL}q=$QUERY"
    if [ -n "$CATEGORIES" ]; then
        URL="${URL}&categories=$CATEGORIES"
    fi
    if [ -n "$PURITY" ]; then
        URL="${URL}&purity=$PURITY"
    fi
    if [ -n "$COLORS" ]; then
        URL="${URL}&colors=$COLORS"
    fi
    if [ -n "$SORTING" ]; then
        URL="${URL}&sorting=$SORTING"
    fi
    if [ -n "$MIN_RES" ]; then
        URL="${URL}&atleast=$MIN_RES"
    fi
    if [ -n "$RATIOS" ]; then
        URL="${URL}&ratios=$RATIOS"
    fi
    if [ -n "$PAGE" ]; then
        URL="${URL}&page=$PAGE"
    fi
    if [ -n "$TOPRANGE" ]; then
        URL="${URL}&topRange=$TOPRANGE"
    fi
    # API_KEY is sourced from current environment variables
    if [ -n "$WALLHAVEN_API" ]; then
        URL="${URL}&apikey=${WALLHAVEN_API}"
    fi
    echo $URL
}

fetch_wallpaper() {
    generate_url

    # Fetch any data just to get amount of images and pages
    DATA=$(curl -s $URL)
    ALL_IMAGES=$(echo $DATA | jq ".meta.total")

    # Get total amount of pages
    TOTAL_PAGES=$(echo $DATA | jq ".meta.last_page")

    # Check whether we want to fetch more pages than we have in response
    if [ "$TOTAL_PAGES" -lt "$FETCH_PAGES" ]; then
        FETCH_PAGES=$TOTAL_PAGES
    fi

    # Randomize page
    PAGE=$(((RANDOM % FETCH_PAGES) + 1))

    # Check whether page is last, therefore use the rest of the images and not default 24 per page limit
    if [ "$PAGE" -eq "$TOTAL_PAGES" ]; then
        INDEX=$((ALL_IMAGES % 24))
        if [ "$INDEX" -eq 0 ]; then
            INDEX=24
        fi
    else
        INDEX=24
    fi

    # Get random image from page
    INDEX=$((RANDOM % INDEX))

    # Generate url to fetch needed page
    generate_url

    # Get image
    IMAGE_URL=$(curl -s $URL | jq -r ".data[$INDEX].path")

    if [ "$IMAGE_URL" != "null" ] && [ -n "$IMAGE_URL" ]; then
        IMAGE="${WALLPAPER_DIR}${IMAGE_URL##*/}"
        echo "Making request to Wallhaven"
        notify-send -u low "Fetching wallpaper from wallhaven" -i "image-x-generic"
        echo $IMAGE_URL
        curl -s -o $IMAGE -w "%{http_code}" "$IMAGE_URL"
        set_wallpaper
    else
        echo "Couldn't access Wallhaven"
        set_default_wallpaper
        notify-send -u normal "Couldn't load image from wallhaven" -i "image-x-generic"
    fi
}

set_default_wallpaper() {
    IMAGE=$(find "$WALLPAPER_DEFAULT_DIR" -type f | shuf -n 1)
    set_wallpaper
}

# Loop to change wallpaper every 15 minutes (900 seconds)
while true; do
    kill_instance
    fetch_wallpaper
    sleep 900 # Sleep for 15 minutes
done
