#!/bin/bash
#  __  __     __  __     ______   ______     __  __     ______     __   __   ______     __   __
# /\ \_\ \   /\ \_\ \   /\  == \ /\  == \   /\ \_\ \   /\  __ \   /\ \ / /  /\  ___\   /\ "-.\ \
# \ \  __ \  \ \____ \  \ \  _-/ \ \  __<   \ \  __ \  \ \  __ \  \ \ \'/   \ \  __\   \ \ \-.  \
#  \ \_\ \_\  \/\_____\  \ \_\    \ \_\ \_\  \ \_\ \_\  \ \_\ \_\  \ \__|    \ \_____\  \ \_\\"\_\
#   \/_/\/_/   \/_____/   \/_/     \/_/ /_/   \/_/\/_/   \/_/\/_/   \/_/      \/_____/   \/_/ \/_/
#
# Requires jq and needs to be ran on start alongside of hyprpaper. Can be ran multiple times

URL="https://wallhaven.cc/api/v1/search?"
WALLPAPER_DIR="/tmp/"
WALLPAPER_DEFAULT_DIR="${HOME}/.local/share/wallpapers/"

RELOAD_FILE="/tmp/.hyprhaven_reload"

# Setting up search query params
# https://wallhaven.cc/help/api#search

COLORS=("663399" "333399" "0066cc")

COLOR=${COLORS[$RANDOM % ${#COLORS[@]}]}

PAGE=$(((RANDOM % 5) + 1))

INDEX=$((RANDOM % 20))

CATEGORIES=010

PURITY=100

SORTING="views"

MIN_RES="1920x1080"

RATIOS="16x9,16x10,21x9"

kill_instance() {
    SCRIPT_NAME=$(basename "$0")
    CURRENT_PID=$$

    if [ $(pgrep -f "$SCRIPT_NAME" | wc -l) -gt 2 ]; then
        OLD_PIDS=$(pgrep -f "$SCRIPT_NAME")
        for PID in $OLD_PIDS; do
            if [ "$PID" != "$CURRENT_PID" ]; then
                echo "Killing old instance with PID: $PID"
                touch $RELOAD_FILE
                kill "$PID"
            fi
        done
    else
        rm $RELOAD_FILE
    fi
}

set_wallpaper() {
    for WALLPAPER in $(hyprctl hyprpaper listloaded); do
        hyprctl hyprpaper unload "$WALLPAPER"
    done

    for monitor in $(hyprctl monitors | grep "Monitor" | cut -d " " -f 2); do
        hyprctl hyprpaper preload $IMAGE
        hyprctl hyprpaper wallpaper "$monitor,$IMAGE"
    done
}

generate_url() {
    if [ -n "$CATEGORIES" ]; then
        URL="${URL}&categories=$CATEGORIES"
    fi
    if [ -n "$PURITY" ]; then
        URL="${URL}&purity=$PURITY"
    fi
    if [ -n "$COLOR" ]; then
        URL="${URL}&colors=$COLOR"
    fi
    if [ -n "$SORTING" ]; then
        URL="${URL}&sorting=$SORTING"
    fi
    if [ -n "$MIN_RES" ]; then
        URL="${URL}&atleast=$MIN_RES"
    fi
    if [ -n "$RATIOS" ]; then
        URL="${URL}&ratios=$RATIOS"
    fi
    if [ -n "$PAGE" ]; then
        URL="${URL}&page=$PAGE"
    fi
    # API_KEY is sourced from current environment variables
    if [ -n "$WALLHAVEN_API" ]; then
        URL="${URL}&apikey=${WALLHAVEN_API}"
    fi
}

fetch_wallpaper() {
    generate_url
    IMAGE_URL=$(curl -s $URL | jq -r ".data.[$INDEX].path")
    if [ "$IMAGE_URL" != "null" ] && [ -n "$IMAGE_URL" ]; then
        IMAGE="${WALLPAPER_DIR}${IMAGE_URL##*/}"
        echo "Making request to Wallhaven"
        echo $IMAGE_URL
        curl -s -o $IMAGE -w "%{http_code}" "$IMAGE_URL"
        set_wallpaper
    else
        echo "Couldn't access Wallhaven"
    fi
}

set_default_wallpaper() {
    IMAGE=$(find "$WALLPAPER_DEFAULT_DIR" -type f | shuf -n 1)
    set_wallpaper
}

# Loop to change wallpaper every 15 minutes (900 seconds)
while true; do
    kill_instance
    # Check if first launch
    if [ ! -e "$RELOAD_FILE" ]; then
        set_default_wallpaper
        sleep 30
    fi
    fetch_wallpaper
    sleep 900 # Sleep for 15 minutes
done
